### ISSUE TITLE
Enable .encryption = .none Option For Login

### ISSUE THREAD

**Issue by arshidkv12** [karlseguin/smtp_client.zig#2]
I need to test with https://mailmulg.net. 

```zig
fn authLogin(self: *Self) !void {
	//if (self.config.encryption == .none) {
	//	return error.InsecureAuth;
        //} 		
```

It is working, if I commended as above.

**Comment by karlseguin** [comment]
This is what `.insecure` is for. It doesn't do anything special, it just doesn't trigger that condition. It's done this way so that you're aware that you're doing something "insecure" and are ok with it.

**Comment by arshidkv12** [comment]
Thank you. Now it is working.
 ```zig
const config = smtp.Config{
        .port = 2525,
        .encryption = .insecure,
        .host = "smtp.mailmug.net",
        .allocator = allocator,
        .username = " ",
        .password = " ",
    };
```
